# dance-studio-mvp/docker-compose.yml
version: '3.8'
services:
  postgres_db:
    image: postgres:13 # Or latest stable version
    container_name: dancestudio_postgres_mvp
    environment:
      POSTGRES_USER: habimana       # Same as in .env
      POSTGRES_PASSWORD: showdem2020 # Same as in .env
      POSTGRES_DB: dancestudio_mvp  # Same as in .env
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Optional: Mount an init script to create tables
      - ./db_init:/docker-entrypoint-initdb.d 
      # This will run any .sql files in db_init when the container first starts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U habimana -d dancestudio_mvp"]
      interval: 10s
      timeout: 5s
      retries: 5


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  # Set default admin email
      PGADMIN_DEFAULT_PASSWORD: admin  # Set default admin password
    ports:
      - "80:80"  # Expose pgAdmin on port 80
    depends_on:
      - postgres_db  # Ensure pgAdmin starts after PostgreSQL
    volumes:
      - pgadmin-data:/var/lib/pgadmin  # Persist pgAdmin data



volumes:
  postgres_data: # Persists data even if container is removed
  pgadmin-data: # Persists pgAdmin data even if container is removed